(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 160,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/bg.jpg", id:"bg"},
		{src:"images/Bitmap1.png", id:"Bitmap1"},
		{src:"images/cahracther2.png", id:"cahracther2"},
		{src:"images/color_circle.png", id:"color_circle"},
		{src:"images/pointershade.png", id:"pointershade"},
		{src:"images/shadecurl.png", id:"shadecurl"},
		{src:"images/shutterstock_177762983_2.png", id:"shutterstock_177762983_2"}
	]
};



// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,970,250);


(lib.Bitmap1 = function() {
	this.initialize(img.Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,450,323);


(lib.cahracther2 = function() {
	this.initialize(img.cahracther2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,246,175);


(lib.color_circle = function() {
	this.initialize(img.color_circle);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,246,175);


(lib.pointershade = function() {
	this.initialize(img.pointershade);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,50,340);


(lib.shadecurl = function() {
	this.initialize(img.shadecurl);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,257,306);


(lib.shutterstock_177762983_2 = function() {
	this.initialize(img.shutterstock_177762983_2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,174,163);


(lib.vy78by = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shadecurl();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,257,306);


(lib.Tween12 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F79420").s().p("Ag0B+QgZgKgTgTQgSgSgLgZQgKgZAAgdIABgSIADgSIAGgRIAIgQIAKgOIALgNIANgMIAPgJIAQgIIARgGIASgDIARgBIASABIASADIARAGIAQAIIAPAJIANAMIALANIAKAOIAIAQIAFARIAEASIABASIgBATIgEASIgFARIgIAQIgKAOIgLANIgNAMIgPAJIgQAIIgRAGIgSADIgSABQgcAAgYgKg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-13.6,-13.6,27.4,27.4);


(lib.Tween11 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#076B94").s().p("ADQIzIgXgDIgWgDIgVgFIgWgFIgUgIIgUgJIgTgKIgSgNIgQgNIgPgQIgMgRQgSAagZAUQgaAUgeAMQgPAGgQAEIggAIQgQADgRABIghACIAAAAQg6AAgwgMQgwgMgmgVQgmgWgcgeQgdgegSglQgTgkgJgqQgKgqABgtIgBqZIABgSQABgJADgIIAGgQQADgIAEgHQAEgHAGgHIALgMQAFgHAHgFQAHgFAHgEQAHgEAIgDIAQgGIARgEIASgBIASABIARAEIAQAGIAPAHQAIAEAGAFIANAMIALAMIAJAOIAIAPIAGAQIADARIABASIAAKNIABANIACANIAEAMIAFAKIAHAKIAHAKIAJAIIAKAHIAKAGIALAEIAMACIAMABIAMgBIAMgCIALgEIAKgGQAKgHAIgIIAIgKIAGgKIAFgKIAEgMIADgNIAAgNIAAqOQAAgKACgIQABgJACgIIAGgQQADgIAFgHIAJgOQAFgGAGgGIANgLQAGgGAIgEIAPgHIAQgFQAIgDAJgBIAQgBIARABIARAEIAQAGIAPAHIAOAJIANAMQAGAFAFAHIAJAOIAIAPIAGAQIADARIABASIAAKNIABANQABAGACAHIADAMIAGAKIAGAKIAIAKIAIAIIAKAHIAKAGIALAEIAMACIAMABIAMgBIAMgCIALgEIAKgGIAKgHIAIgIIAIgKIAGgKIAFgKIAEgMIADgNIAAgNIABqNIABgSQABgJACgIQACgIAEgIIAIgPIAJgOIALgMQAGgHAHgFQAGgFAIgEQAHgEAIgDIAQgGIARgEIASgBIARABIARAEIARAGIAPAHIAOAJIAMAMIALAMIAKAOIAHAPIAGAQQACAIABAJIACASIAAKZQgBAtgJAqQgJAqgTAkQgSAlgdAeQgcAegmAWQgmAVgwAMQgwAMg5AAIgWAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-57.2,-56.3,114.5,112.7);


(lib.Tween10 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#076B94").s().p("AhNGLQgmgIgkgQQgjgPgfgWQghgWgbgbQgcgcgVggQgXghgPgkQgQgkgHgoQgJgnAAgpQAAg2AOg0QAPgzAbgtQAbgtAkglQAkgkAtgbQAsgbAygOQAygPA0AAQA1AAAxAPQAyAOAtAbQAsAbAlAkQAkAlAbAtQAaAtAPAzQAPA0AAA2QAAA3gPA0QgPAzgaAtQgbAsgkAmQglAkgsAbQgtAbgyAOQgxAOg1ABQgngBgmgIgAgQiPQgIACgJACIgPAFIgOAHQgIADgGAGQgHAEgGAGIgLALIgKAOIgIAOQgEAIgDAIQgEAIgCAJIgDASIAAABIAAAAIgBARIABATIAEATIAFASIAJARIAJAQIALANIAOANIAOAKIAPAJIASAGIASADQAJACAIgBIAAAAIASgBIASgDIARgGIAQgJIAOgKIANgNIAMgNIAJgQIAIgRIAGgSIAEgTIAAgTQAAgdgKgaQgKgbgTgTQgSgUgZgLQgYgLgdAAIAAAAIgQAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-39.7,-40.4,79.5,80.8);


(lib.Tween9 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#076B94").s().p("AhNIlQgmgIgjgQQgjgPgggWQgfgVgbgcQgbgbgWghQgVgfgPgkQgQgkgIgnQgIgmAAgoIAApIIABgSQABgJADgIIAGgQQADgJAEgHQAEgHAGgGIALgNQAFgGAHgFQAHgGAHgEQAHgEAIgDIAQgGIARgEIASgBIASABIARAEIAQAGIAPAHQAIAEAGAGIANALIALANIAJANIAIAQIAGAQIADARIABASIAADSQBAgYBCAAQA1AAAxAPQAyAOAsAaQAsAbAkAkQAkAlAaAsQAaArAOAzQAOAyABA3QgBA2gOAyQgOAygaAtQgaAtgkAkQgkAkgsAbQgsAagyAPQgxAOg1AAQgnAAgmgIgAgQAPIgRACIgPAGIgPAGIgOAJIgMAKIgLANIgKAMQgFAIgEAHIgHAQIgFAQIgDASIAAABIAAABIgBATIABATIAEATQACAKADAIIAIARQAEAIAGAIIALANIANAMQAHAGAIAFQAHAFAIADIARAGIASAEIASACIAAAAIASgCIASgEIARgGQAIgDAHgFIAPgLIANgMIALgNIAKgQIAIgRIAFgSIAEgTIABgTQAAgggKgaQgLgagSgUQgTgTgYgLQgZgLgcAAIAAAAIgEgBIgMACg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-39.3,-55.8,78.7,111.6);


(lib.Tween4 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#076B94").s().p("AAAGJQgagBgXgJQgYgLgSgSQgSgSgKgXQgKgYAAgcIgBoJQAAgKACgIQABgJACgJQACgIAEgIIAHgPIAKgOIALgMIAMgMQAHgFAHgEQAHgFAIgDQAIgDAJgCQAIgCAJgCQAIgBAIAAIARABIARAEIAQAFQAIADAIAFIAOAJIAMAMIALAMIAKAOIAHAPIAGAQQACAJABAJIABASIABIJIgCASIgDARIgGARIgHAOIgKAPIgLAMIgMAMIgOAJIgQAIIgQAFIgRAEIgRABg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-13.1,-39.3,26.3,78.7);


(lib.gbuiuhiop = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.color_circle, null, new cjs.Matrix2D(1.434,0,0,1.433,-171.7,-127.9)).s().p("AxJQEMAAAggIMAiTAAAMAAAAgIg");
	this.shape.setTransform(171.7,128);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(61.9,25.1,219.8,205.8);


(lib.g67y9p = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.pointershade();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,50,340);


(lib.fvyuibgyiuyo = function() {
	this.initialize();

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#076B94").s().p("AmSCUIACgbIACg0IACg0IACgzIAYgLIAFACIACDUIgoAGgAlPBbIAAgBIALg0IADgJQACgFAFgDIAdgRIALgEIAIgFIANgJIAJgHIAFgHIADgJIABgJIAAgLIgBgLIgDgIQgEgHgHgEIgJgDIgKgCIgLgBIgNAAIgCAAIhXAAIgOgCQgFgBgDgDQgEgDgBgEQgBgFABgHIAGg4IASABQAAAIAGAEIAHADIALABIABAAIBKAAIAUABIAQADQAHACAGADQAGADAFAEQAJAJAEANIADAPIABARIAAAMIgBALIgBALIgBALIgBAKIgBAKIgCAKIgCAJIgFAOIgGANIgHAJIgMAKIgJAGIgMAHIghAVIgHAFIgEAEIgEAEIgCAEgABvBdIAFiNIAAgOIgBgLQgCgKgEgEQgFgEgHgBIgGgBIgIAAIgCAAIgBAAIgIgBIgHAAQgGgBgEgDQgEgDgCgFQgBgEABgIIAGg4IASABIABAIQABADADABIAGADIAIABIABAAIANABIALACQAJAEAGAHIAEAIIADALIACANIAAAQIAAAWIABAWIABAWIABAWIABAUIACAXIAEAyIgoAHgAgqBdIAFi6IhvAAIgBAAIgMgBQgGgBgEgDQgEgCgBgFQgBgEAAgHIAHg6IASABQAAAJAGADIAHADIALABIABAAICYAAIAAAAIgIA+IgJABIgHABQgEABgEADQgDACgBAEQgBAEAAAFIAAAKIAAAPIADAmIADAtIAEA0IgnAHgAC+BZIAAgBIALgwIADgJQABgDAEgBIAKgBIAOgBIAEAAIB2AAIgCgPIgCgMIgBgPIgBgOIgBgbIgBgKIgCgHQgDgHgGgEQgGgEgIgCIgKgBIgKAAIgBAAIhFAAIAAAAIgNgBQgGgBgEgDQgDgDgCgFQgBgEABgIIAGg4IASABQAAAJAGADIAHADIALABIABAAIA5AAIASABIAPADQAHACAFADQAGADADAEQAEAEADAFIAEALIADANIAAAQIAABQIABAMIABAJQABAJADADQAEAEAGABIAHABIAJAAIABABIgIA7IizAAIgBAAIgGAAIgFABIgDACIgCACg");
	this.shape.setTransform(9.4,46.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#076B94").s().p("AgFCbQgNgBgJgIQgIgJgBgPQAAgFACgFQABgFADgEQADgEAEgDQAEgDAEgBQAFgCAGAAQAEAAAEACQAFABADADQAEADADAEQADAEACAFQABAFAAAFQAAAGgBAFQgCAFgDAEQgDAEgEADQgDADgFABQgEACgEAAgAgGA3IgJgFIgJgHIgJgHIgIgJIgGgJIgEgKIgCgIQAAgHACgGQADgGAFgHQAFgHAIgHIAJgHIALgIIAPgLIAPgLQAHgGAFgGQAEgFAAgFQAAgJgGgFQgDgDgEgBIgKgCIgLACIgIADQgKAEgHAGIgNAKQgFAFgCAAQgEAAgEgCIgIgGQgEgEgCgFQgDgFAAgFIABgGIACgEIADgFIAEgEIAJgGIAIgFIAJgDIAJgDIAHgBIAGgBIABAAIAJABIAJACIAJAEIAJAEQAJAGAIAHQAHAHAGAJIAFAJIAEAJIACAKIABALIgBAMQgCAGgCAFQgDAFgFAGQgFAFgIAFIgOAKIgIAGIgIAGQgIAGgFAFQgDAHgBAHIABAIIADAHIADAHIAIAJIgKALIgHgDg");
	this.shape_1.setTransform(-42.5,40.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#076B94").s().p("ACTBlIAEggIADggIACggIAYgJIAGACIgCCBIgpAHgAjOBlIAEggIADggIADggIAXgJIAGACIgCCBIgpAHgAGSCFIAFgUIAGgYIAGgYIAGgYIAGgYIAEgTIADgRIABgNIgBgKQgBgEgDgDQgCgCgDgBIgIgBIgBAAIgNgBQgGAAgEgDQgEgDgCgEQgCgFABgIIAGg5IASABIABABQAAAGACADQACAEAEABQAFABAGAAIAKABIAIACQAIADAEAFQAFAFABAHQACAIAAAJIAAAIIgBAJIgBAIIAJgKIAJgKIAIgLIAIgLIAIgLIAHgMIAyAAQAVABAOAKQANAKAHARIAHASIAEAVIACAXIAAAVIAAAMIAAALIgBAMIgBAMIgBALIgBALIgDAVIgDASIgDAPIhqABIgBAAIgGAAIgFABIgDABIgDADIgQgDIAAgBIALgwIACgIQACgDAEgBIAKgBIAOgBIAEAAIBJAAIACgKIABgKIABgKIAAgLIgBgQIgCgNIgEgOIgGgLQgHgMgNgGQgMgHgUAAIgRABIgOACIgNAEIgKAGQgJAGgHAKIgFALIgFANIgDAJIgDANIgDAOIgDAQIgCARIgCASIgFAoIgoAGgAE2CFIAEiYIAAgKIgBgIQgBgHgDgDQgDgDgGgCIgPgBIgCAAIhyAAIgBAAIgMgBQgGgBgEgCQgDgDgBgFQgCgFABgHIAGg5IASABQAAAJAGAEIAHADIALAAIABAAICBAAIACAAIALAAQAFABADACQAEACABAEQABAEgBAHIgGA8IAKCkIgnAGgAgrCFIAFiYIgBgKIAAgIQgBgHgEgDQgDgDgGgCIgHgBIgIAAIgBAAIhzAAIAAAAIgNgBQgGgBgDgCQgEgDgBgFQgBgFAAgHIAGg5IASABQABAJAFAEIAIADIALAAIABAAICAAAIADAAIAKAAQAFABAEACQADACABAEQABAEAAAHIgHA8IAKCkIgmAGgAkqCFIAFiNIAAgOIgCgLQgBgJgFgEQgEgFgHgBIgOgBIgCAAIgBAAIgPgBQgHgBgEgCQgEgDgBgFQgCgFABgHIAGg5IASABIACAIQABADADACIAGADIAIAAIAAAAIAOABIAKADQAKADAFAIIAFAIIADALIABANIABAPIAAAXIAAAWIABAUIABAWIACAWIABAXIAEAyIgnAGgAnABiIgRgRIgRgQIgSgQIgSgQIgUgSIgWgSIgFAJIgCAJIAAAFIAAAFIADAIIAGAOIAFAKIAGANIgIA5IgvABIgBAAIgGAAIgFABIgDABIgDADIgQgDIAAAAIAKgwIACgIQACgDADgBIALgCIAPAAIADAAIAFAAIgGgPIgEgLIgBgIIgBgFIABgFIADgKIAGgOIAEgIIAFgKIgTgQIgLgLQgEgEgBgDQgBgDAAgEIAKhLIASABIACAMQABAGADAHQAEAHAGAHIAHAIIAJAIIAnAhIAnAiIAUgqIgKgBQgFgBgDgCQgDgDgBgEQgCgFABgHIAGg6IASABQAAAJAGAEIAHADIALAAIABAAIAuAAIAAABIgIA9IgNABIgKACIgIAEIgHAFIgHAIIgHAKIgHANIgIAOIAkAhIAjAhIgKBAIgNABg");
	this.shape_2.setTransform(-0.9,-4.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#076B94").s().p("AE+CGIAEiZIAAgKIgBgIQgBgGgDgEQgDgDgHgBIgPgBIgBAAIhpAAIABC0IgnAGIgBgBIAQi5IgNgBQgFgBgEgDQgDgDgBgEQgCgFABgIIAGg4IASABQAAAJAGAEIAIACIAKABIABAAICOAAIACAAIALAAQAFAAADACQAEACABAEQABAEgBAHIgHA8IALClIgnAGgAhlCCIgBAAIALgxIADgJQACgCADgCIAKgBIAPAAIADAAIBtAAIAEgOIADgOIACgPIABgRIgBgKIgCgMIgEgLIgHgJQgDgEgFgDIgMgFQgGgDgIgBIgQgBIg/AAIAAAAIgNgBQgGgBgDgDQgEgDgCgEQgBgFABgIIAGg4IASABQAAAJAGAEIAHACIALABIABAAIAwAAQAbAAARAJQARAJAJAPQAFAIADAKQAEAIABAKIADAVIABAXIgBAPIgBAQIgDAQIgEAQIgFAQIgFAQIgHARIgHATIiAABIAAAAIgHAAIgEAAIgDACIgDACgAlcA0IAAgNIABgNIABgNIABgNIADgLIACgOIADgNIAEgOIgKgBQgFgBgDgCQgDgDgBgFQgBgEAAgHIAGg6IASABQABAJAFAEIAIACIALABIABAAIBWAAQAbAAAQAGQAPAGAIAMQADAGACAHQADAHABAJIABASIAAAVIAAAOIAAAQIgBAVIgBAMIgBALIgBANIgBANIgCANIgCANIgCANIgDANIi0ABQgKgoAAglgAk2guIgCALIgCAOIgCAQIgBAOIgBAQIABARQABAHACAGQACAFAEADQAFADAHABIBkAAQAHAAAFgDQAEgCADgGIACgGIABgJIABgLIAAgOIAAgRIAAgPIgCgMIgEgKQgCgEgEgDQgEgCgFgCIgNgDIgIAAIgJAAIhVAAg");
	this.shape_3.setTransform(4.9,-51.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#076B94").s().p("AgfA/IgGgQIAKgEIAHgFQAHgEAFgFQAFgFADgGQAAgGAAgHQAAgKgGgIQgJgJgOgDQgCAAgCgEQgDgEAAgGQAAgEACgEIADgGIAHgFIAHgDIAHgBQAGAAAEACIALAFQAFADAFAFQAFAFADAGQAEAGADAHIABAIIABAIQAAAHgCAFQgCAHgDAGIgHALIgJAJIgLAIIgKAHIgMAGIgNAEg");
	this.shape_4.setTransform(-38.2,-39.1);

	this.addChild(this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-64.6,-64.9,127.6,129.1);


(lib.ftyugyuop = function() {
	this.initialize();

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#076B94").s().p("AIZBwIAAAAIAAh4QAAghgnAAIgPAAIgRABIgRACIgNABIgLACIAAgBIAAghIAOgDIAVgCIAWgBIAUgBIASABIAOABIAMADIAKAEQAJAEAGAFIAFAGIAEAIQADAIABAIIABAJIAAALIAAB4IAAAAgAGpBwIAAh1IAvAAIABAAIAAB1IgBAAgAEoBwIgBAAIAAgiIABAAIAlAAIAAhDIgCgTQgBgJgDgGIgFgIQgHgJgQAAQgHAAgGADQgHADgEAFIgIAIIgFAIIgCADIgLB6IgvAAIAAAAIAMh0IAAgOQAAgZgLgdIAAgBIAtAAIAFANIAEAQIADAAIACgEIACgCIAEgFQAFgGAGgEIAIgEIAJgDIAMgDIAMgBIANACIAMADIAKAGIAIAHIAGAIIAFALQAIATAAAaIAABqIgBAAgABEBwIAAgiIAAAAIAwAAIACgOIABgTIAAg+QAAgRgJgEQgEgCgFAAIgMAAIgMACIAAAAIAAgjIAOgCIAOgBIAOABIAMACIAKAEIAHAEQAHAFAEAIQAHANAAAWIAABJIAAAOIgCAOIgBAMIgCAJIgCAHIhbAAgAgJBwIgBh4QAAgRgJgIQgKgIgUAAIgPAAIgRABIgQACIgNABIgLACIgBgBIAAghIAPgDIAUgCIAWgBIAVgBIARABIAPABIAMADIAIAEQAIAEAGAFIAFAGIAEAIQADAIABAIIABAJIAAALIAAB4IAAAAgAh6gFIAwAAIAAB1IgvAAgAjyBwIARhFIAZhRIhoAAIAAgBIAAhIIAvAAIABAAIAAAmIBoAAIABABIAAAcIgbBXIgRBFIguAAgApIBwIAAAAIAAi1IAPgDIAUgCIAXgBIAVgBQArAAATANQATAOAAAcIAACFIAAAAgAoKgpIgOABIAAB2IBAAAIAAhjQAAgMgLgEIgLgDIgRgBgAl8AxIgBAAIAAh5IABgBIAvAAIAAABIAABUIgfAlg");
	this.shape.setTransform(0.1,127);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#076B94").s().p("AiKBeQgIgBgIgEQgPgGgLgMQgLgMgGgSQgEgJgBgLQgCgKAAgLIAAhbIABgBIAvAAIAAABIAABbQAAAeAJAPQAJAPASAAQASAAAJgOQAJgPAAgfIgBgZQgBgLgDgHQgEgMgMgDIgOgBIgKABIAAgBIAAggIAMgDIAMgBQAZAAAOAJQAfASAABEQAAAugXAZQgWAZgqAAQgIAAgIgCgAHFBdIAAAAIAAi5IAAAAIAvAAIABAAIAAC5IgBAAgAEIA7IBZAAIAAhWQAAgRgKgIQgJgIgUAAIgVABIgWABIgHABIAAAAIAAgjIAZgCIAfgBQAyAAARASQAEAFADAGQADAFABAGIACANIABAPIAABWIAWAAIABAiIigAAgABPBdIAAAAIAAgiIAAAAIBZAAIAAhWQAAghgmAAIgVABIgWABIgIABIAAAAIAAgjIAagCIAfgBQAyAAAQASQAFAFACAGQADAFACAGIACANIAAAPIAABWIAXAAIAAAAIAAAiIAAAAgAknBdIAAAAIAAi5IAAAAIAvAAIABAAIAAC5IgBAAgAmEBdIAAh4QAAgRgJgIQgKgIgTAAIgMAAIgOABIAACYIAAAAIgvAAIgBAAIAAi1IAPgDIAUgCIAWgBIAVgBIARABIAPABIAMADIAKAEQAJAEAFAFQAGAGADAIIADAIIABAIIABAJIAAALIAAB4IgvAAgAAAAeIAAh6IAAAAIAvAAIABAAIAABWIggAkIgQAAg");
	this.shape_1.setTransform(0.1,92.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#076B94").s().p("AnPBfIgLgDIAAgiIAAAAQALACAGABQAFgBAEgBQAEgCACgEQADgGAAgKIAAhdIgWACIgBgBIAAghQAYgEAYgBQAYgCAXAAQAjAAARAIQAJAFAGAFIAFAGIAEAIQADAIABAIIABAJIAAALIAAB3IAAABIgwAAIAAgBIAAh3QAAgRgKgIQgKgIgTAAIgJAAIgKAAIAABhQAAAigRAOIgIAFIgKADIgLACIgNABIgMgBgAGrBdIAAgBIAAh3QAAgRgKgIQgJgIgUAAIgPAAIgRABIgQACIgNABIgMACIAAgBIAAghIAPgDIAUgCIAWgBIAUgBIASABIAPABIAMADIAJADQAJAFAGAFIAFAGIAEAIQADAIABAIIABAJIAAALIAAB3IAAABgAE7BdIAAh1IAwgBIAAABIAAB0IAAABgACrBcIhaABIgSi4IABgBIAtAAIAJBcIAEAAQAMAAAGgFQADgCACgGQABgFABgHIAGhCIAtgBIAAABIgFBCQgFA3g7AAIgIAAIACAdIAyAAQAaAAAOgTQANgTADgeIAIhSIAtgBIABABIgIBRIgDAVIgFATQgVA/hLAAgAgTBdIAAi4IAAgBIAtAAIABABIAAC3IgBABgAiiA7IAAAAIAwAAIACgOIABgTIAAg+QAAgRgJgEQgDgCgGAAIgMAAIgLACIgBAAIAAgjIAOgCIAPgBIAOABIALACIAKAEIAIAEQAHAFAEAIQAHANAAAWIAABJIgBAOIgBAOIgCAMIgCAJIgCAHIhbAAgAjyBcIAAi3IAAgBIAwAAIAAABIAAC3IgwABg");
	this.shape_2.setTransform(-0.6,56);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#076B94").s().p("ACECCIAAAAIAAi1IAAAAIAsAAIAAAAIAAC1IAAAAgAnaA9IgLgDIAAgiIAAAAQAKACAGAAQAGAAAEgCQAEgCABgDIADgHIAAgJIAAheIgWACIAAAAIAAghQAYgEAYgBQAXgCAYAAQAjAAARAIQAJAFAGAFQAFAFADAJIADAIIACAIIAAAJIABALIAAB3IgBABIgvAAIAAgBIAAh3QAAghgnAAIgJAAIgKAAIAABhQAAAigSAOIgHAEIgKAEIgLACIgNABIgMgBgAFGA7IAAgiIAAgBIBZAAIAAhVQAAghgmAAIgVAAIgWACIgIABIAAAAIAAgjIAagCIAfgBQAyAAAQASQAFAFACAFQADAGABAGIADANIAAAPIAABVIAXAAIAAABIAAAhIAAABgADMA7IgBgBIAAgFIABgNIAEgTIAEgTIAFgPIAfhPIh0AAIAAAAIAAgiIAAAAICoAAIABAAIAAAbIgiBVQgQAmAAAdIAAAFIAAABgAAog9QAAghgnAAIgUAAIgcADIAAgBIAAgiIAbgCIAWgBIAUABIAQABIAMADIAKADQAIAFAGAFQAGAFADAJIACAIIACAIIABAJIAAALIAAB3IgvABgAitA6IAAghIAAgBIAwAAIACgNIABgRIAAhBQAAgQgJgFQgEgBgFAAIgMAAIgMACIAAAAIAAgjIAOgCIAPgBIANABIAMACIAKADIAIAFQAGAFAEAIQAHANAAAVIAABKIAAAOIgBAOIgCAMIgCAIIgCAHIhbABgAj9A7IAAi5IAAAAIAvAAIABAAIAAC4IgBABg");
	this.shape_3.setTransform(0.3,22.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#076B94").s().p("AoQBxIAAAAIAJglIAGgjIAsgBIADAEQgFAPgHARIgQAlgADzBOIgTgBIgPgBIgLgBIgIgBIAAggIAAgBIAkACIAkABQANAAAJgHQADgDADgFIAEgLIACgJIABgJIABgQIAAgNIgBgLIgDgMIgEgKQgCgFgEgDQgJgHgNAAIgJABIgIACQgHADgDADQgEAEgCAEQgCAHAAAGQAAAHACAFQADAGAFADQAIAGAHABIAGABIAAABIgIAfIgIgBIgTgDIgNgEQgggMAAgoIABgOIAEgNIAGgKIAIgJIAJgGIAKgGQAUgIAaAAIAMAAIAMACIALADIALAFIALAIIAJAJQAEAFADAHIAGAQIAEASIABAUIAAASIgCANIgDANIgEALIgEAJIgGAIQgGAIgHAFQgHAEgJADQgHADgJABIgTABgAh3A1QgWgaAAgrQgBgJACgIQACgJAEgIQAHgRAJgIIAAgBIgUACIgBgBIAAghQATgCAUgBIArgBQAnAAAVAZQAWAaAAAtQAAArgXAaQgUAZgnAAQgnAAgXgZgAhLhNQgSAXAAAmQAAAcAJAPQAJAPASAAQAjAAAAg7QAAg9gjAAgAFyBLIgBAAIAAgiIABAAIBZAAIAAhWQAAghgnAAIgVABIgWACIgHABIgBgBIAAgiIAagDIAfAAQAyAAARASQAEAFADAFQADAFABAGIACANIABAPIAABWIAWAAIAAAAIAAAiIAAAAgAAuBLIAAgiIAAAAIAwAAIACgOIAAgTIAAg+QAAgQgIgFQgEgCgGAAIgLABIgMACIAAgBIAAgiIAOgDIAOAAIAOAAIAMADIAKADIAHAFQAHAFAEAIQAHANAAAVIAABKIAAANIgCAOIgCAMIgCAJIgBAHIhbAAgAk7BLIAAAAIAAh4QAAgQgKgIQgKgJgTAAIgPABIgRABIgQABIgOABIgLACIAAAAIAAgiIAPgCIAUgCIAWgCIAUAAIASAAIAOACIAMACIAKAEQAJAEAGAGQAGAFADAIQADAIABAJIABAJIAAAKIAAB4IAAAAgAmrBLIAAh1IAvAAIABAAIAAB1IgBAAgAjgAMIAAAAIAAh5IAAAAIAvAAIABAAIAABWIggAjg");
	this.shape_4.setTransform(0.2,-15.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F79321").s().p("AgiBfIgagDIAAgjIAAAAIAaACIAaABQAYgBAIgSQADgFABgHIABgOIAAgdQAAghgUgKIgIgCIgJgBIgXAAIgdADIAAgBIAAghIAdgDIAdgBIAQABIAPAEIANAGIAKAHIAIAJIAHAKQAKAVAAAcIAAATIAAANIgCAMIgCAMIgFALIgGALIgIAJIgKAHIgNAGQgIACgIABIgRACIAAAAIgggBgAB/BGQgWgZAAgtQAAgHACgJQABgIAEgJQAHgRAJgIIAAAAIgUABIAAAAIAAghQASgDAUgBIArgBQAoAAAWAaQAWAZAAAsQAAAtgWAZQgXAagnAAQgnAAgXgagACsg8QgTAYAAAkQAAA8AkAAQAjAAAAg8QAAgegIgPQgJgPgSAAgAkKBfIgLgDIAAgiIAAAAIAJACIAHAAQAGAAAEgCQADgCACgDIACgHIABgJIAAheIgWADIAAgBIAAghQAYgEAXgBQAYgCAYAAQAiAAASAIQAJAFAFAFQAGAGADAIQADAIABAIIABAJIAAALIAAB3IAAABIgvAAIgBgBIAAh3QAAghgmAAIgJAAIgKAAIAABhQAAAigSAOIgIAEIgJAEIgLACIgNABIgMgBgAGlBdIgBgBIAAh3QAAghgnAAIgLAAIgOABIAACXIAAABIgvAAIgBgBIAAi0IAPgDIAUgCIAWgBIAVgBIARABIAPABIAMADIAKADQAIAFAGAFQAGAGADAIQADAIABAIIABAJIAAALIAAB3IAAABgAnTBdIAAgBIAAi0IAOgDIAVgCIAWgBIAWgBQArAAATANQATANAAAdIAACEIgBABgAmWg8IgNABIAAB1IBAAAIAAhiQAAgNgLgEIgMgCIgQgBg");
	this.shape_5.setTransform(0.1,-53.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#076B94").s().p("AnYCCIgBAAIAAijIgBgVIgCgOIgEgLQgDgEgDgDQgJgHgNAAIgJABIgIACQgHACgDAEQgEADgCAFQgDAGAAAHQAAAGADAGQADAGAFADIAIAFIAHACIAGABIAAAAIgIAhIgIAAIgTgEIgOgEQgfgNAAgoIABgPIAEgMIAGgLIAHgIIAJgHIALgFQAUgJAaAAQAdAAAUAMQAHAFAHAIIAGAIIAFAJQAKAWAAAgIAACjIAAAAgAHgA9IgagDIAAgjIABAAIAZACIAaABQAaAAAIgSQADgGABgEIABgPIAAgeQAAgigUgJIgIgDIgLgBIgWABIgdACIgBAAIAAgiIAdgDIAdgBIASACIAPADIANAGIAKAHIAIAJIAHALQAKAUAAAcIAAAVIAAANIgBAKIgDAMIgFAMIgGAKIgIAJIgKAHIgNAGIgQAEIgTABIgggBgAiQA+IgggBIgagDIAAgjIAAAAIAZACIAbABQAaAAAIgSQACgGABgEIACgPIAAgeQAAgigUgJIgJgDIgKgBIgXABIgdACIAAAAIAAgiIAcgDIAegBIARACIAPADIANAGIALAHIAIAJIAGALQALAUAAAcIAAAVIgBANIgBAKIgDAMIgEAMIgHAKIgHAJIgLAHIgNAGIgQAEIgSABgAlwAkQgWgZAAgsQAAgIABgJQACgIAEgJQAHgQAJgIIAAgBIgUACIAAgBIAAghQASgDAUgBIArgBQAnAAAXAaQAWAZAAAtQAAAsgXAZQgWAagnAAQgnAAgXgagAlEheQgSAYAAAlQAAAfAJANQAJAPASAAQAjAAAAg7QAAg9gjAAgAFTA7IAAAAIAAgiIAAAAIAlAAIAAhAIgCgXQgBgJgCgFIgGgIQgHgJgPAAQgHAAgHADQgHADgEAFIgIAIIgFAIIgBADIgMB6IgvAAIAAAAIAMh0IAAgOQAAgZgLgdIAAgBIAuAAIAFANIAEAPIACAAIACgCIAGgIQAFgGAGgEIAIgEIAJgDIAMgDIANgBIAMACIAMADIAKAGIAIAHIAGAJIAFAKQAIATAAAcIAABoIgBAAgAChA7IAAAAIAAh4QAAghgnAAIgPAAIgRABIgQACIgNABIgMABIAAAAIAAghIAPgDIAUgCIAWgBIAUgBIASABIAPABIAMADIAJAEQAJAEAGAFQAGAGADAIIACAIIACAIIABAJIAAALIAAB4IAAAAgAAxA7IAAAAIAAh1IAAgBIAwAAIAAABIAAB1IAAAAg");
	this.shape_6.setTransform(-0.1,-86.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#076B94").s().p("AghBSIAxgHIgqiYIAAAAIAtAAIAZBSIAMA7QAMgIAHgNQADgGADgJQACgJABgKIAIhWIAvAAIAAAAIgHBPQgCANgCALQgDALgDAIQgWAzhIAMIg9AIgAH8BuIgJgBIADgpIAAAAIAEAAIAHABIAKAAQAGgBAJgCQAMgEAHgKQAHgKAAgNIAAgzQAAgQgJgEQgDgCgGAAIgNAAIgKACIgEABIAAAAIAAgjIAOgDIARgBIAPABIANACIAKAEIAHAEQAHAFAEAIQADAIACAIIAAAIIABAKIAACBIgBABIgjAAIgIgbIgBAAIgIAJIgKAKQgGAEgJADIgJADIgIABIgCAAIgHgBgAimBuIgZgDIgBgjIABAAIAZACIAaAAQAaAAAJgSQACgFABgHIABgOIAAgeQAAgggTgKIgJgCIgKgBIgXAAIgdADIgBgBIAAghIAdgDIAdgBIASABIAPAEIANAGIAKAHIAIAJIAHAKQAKAVAAAaIAAAVIAAANIgBAMIgDAMIgFALIgGALIgIAJIgKAHIgNAGIgQADIgSACIghgBgAGMBrIAQhFIAahRIhoAAIgBAAIAAhIIABAAIAvAAIAAAAIAAAmIBpAAIAAAdIgbBWIgRBGIguAAgAD/BsIAAgBIAAi4IAAAAIAwAAIAAAAIAAC4IAAABgAmiBsIgSi5IABAAIAtAAIAJBbIAEAAQAMAAAGgGQADgDACgFQABgDABgHIAGhDIAtAAIAAAAIgFBDQgFA3g7AAIgJAAIADAcIAyAAQAaAAANgSQAOgTADghIAIhQIAtAAIABAAIgIBPIgDAYIgFASQgVBAhLAAgApiBsIgBgBIAAi4IABAAIAvAAIAAAAIAAC4IAAABgAoHAtIAAh6IAAAAIAwAAIAABUIgfAmIgRAAg");
	this.shape_7.setTransform(0.1,-127.9);

	this.addChild(this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-61,-139.6,122.4,277.9);


(lib.f67y9p = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgRDDIAAgIIAjgWIAAABIAAAJIgIAFIAAAXIAIAEIAAAJgAgJC/IAMAIIAAgPgAgRCgIAAgKIAYgPIgYgNIAAgJIABgBIAiAVIAAAGIgiAVgAgRBkIAAgfQAAgJAHAAIAJAAQAFAAAAAJIAAADIAOgQIAAABIAAAMIgOAPIAAAHIAOAAIAAAJgAgKBGIAAACIAAATIAJAAIAAgTIAAgCIgCgBIgEAAIgDABgAASAwIgjgVIAAgJIAjgTIAAAAIAAAIIgIAFIAAAWIAIAEIAAAKgAgJAXIAMAHIAAgPgAgRgPIAAgJIAOAAIAAgaIgOAAIAAgJIAjAAIAAAJIgPAAIAAAaIAPAAIAAAJgAAShJIgjgVIAAgIIAjgWIAAABIAAAJIgIAFIAAAXIAIAEIAAAJgAgJhiIAMAIIAAgPgAgRiJIAAgIIAUgRIgUgRIAAgHIAjAAIAAAJIgVAAIgCgBIASAQIABACIgTAPIACAAIAVAAIAAAIgAAKjLIgDgBIgBgCIAAgIIABAAIADgBIAFAAIADABIAAADIAAAHIgBABIgCAAg");
	this.shape.setTransform(1.9,21.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,3.7,43.3);


(lib.dct7vyp = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AARAOIgBgRIDEhcIAAABIAAAcIidBFICdA/IAAAdIAAABgAjTAOIAAgRIDDhcIABABIAAAcIieBFICeA/IAAAdIgBABg");
	this.shape.setTransform(21.3,9.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,42.6,19.3);


(lib.dc7yvt9p = function() {
	this.initialize();

	// Layer 4
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.shutterstock_177762983_2, null, new cjs.Matrix2D(0.998,0,0,0.994,-86.8,-77.6)).s().p("AtiMIIgBgBIAA4NIABgBIbGAAIAAABIAAYNIAAABg");
	this.shape.setTransform(-0.3,-119.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#076B94").s().p("ADjDHIAAgBIALg2IADgJQACgEAEgDIAvgZIAPgJIAOgJQADgEADgHQADgGABgJIABgJIABgKQgBgIgCgGQgDgFgFgDQgFgDgHgBIgQgBIhbAAIgNgBQgFgBgEgDQgDgCgBgEQgCgCABgGIAJh1IgKgBQgFgBgCgCQgDgDgBgEQgBgEABgHIAGg4IASABQAAAJAFAEIAHACIALABIATAAIAAAAIgHA7IgIACQgDABgBACIgDAGIgBAHIgDAjIAAAJIAAAHIACAEQACABADABIAJABIBQAAQAeAAAPAOQAPAOAAAbIgBAYIgKBBIgDALIgEALIgEAJQgEAJgFAFIgMAKIgRAKIgrAZIgGAFIgFAEIgGAIIAAAAgAgaDJIAEibIAAgKIgBgIQgBgGgDgEQgEgDgGgBIgGgBIhzAAIABC1IgnAHIgBgBIAPi7IgMgBQgGgBgDgDQgDgDgBgFQgCgCABgIIAGg4IASABQAAAJAGADIAIADIAKABICbAAQAFAAACACQADACACAEQABAEgBAHIgHA6IALCmIglAHgAoVDJIAFiPIAAgOIgBgLQgCgKgFgEQgEgEgHgBIgRgBIgPgBQgHgBgEgDQgEgDgBgFQgCgCABgIIAGg4IASABIACAIQABADADABIAGADIAIABIABAAIANABIALACQAJAEAGAHIAEAIIADALIABANIABAOIAJC3IgnAHgAGRDFIAAgBIALgwIACgJQACgDADgBIALgBICAgBIAEgNIADgOIACgQIABgQIgBgMIgCgMIgEgLIgGgJQgEgEgFgDIgLgGQgHgCgIgBIgRgBIhAAAIgNgBQgGgBgDgDQgEgDgBgFQgCgCABgIIAGg4IASABQAAAJAGADIAHADIALABIAzAAQAbAAARAJQARAJAJAPQAFAIADAIQAEAIACAKIACAVIABAWIAAASIgCAQIgDAQIgEAQIgYBEIiCAAIAAAAIgGAAIgFABIgDACIgDACgAkwBqIAUgsIAGgQQACgHAAgGQAAgFgCgEQgBgEgEgCQgDgDgGgBIgPgBIgIAAIgNgBQgFgBgEgDQgEgCgBgFQgCgCABgHIAHg5IAQAAQABAGACADQABADAEACIAIABIALABIANAAIAKADQAJACAGAGQAFAFADAJIACAIIAAAKIAAAIIgSBiIgoAGgAmnBqIATgsIAGgQQACgHAAgGQAAgFgBgEQgCgEgDgCQgEgDgGgBIgPgBIgIAAIgMgBQgGgBgEgDQgEgCgBgFQgBgCAAgHIAHg5IAQAAQABAGACADQABADAEACIAIABIALABIANAAIAKADQAJACAGAGQAGAFACAJIACAIIABAKIgGAtIgNA9IgoAGg");
	this.shape_1.setTransform(2.1,187.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#076B94").s().p("AjXhGIgBgIQgBgGgDgEQgDgDgGgBIgQgCIhTAAIgMgBQgGgBgEgCQgDgDgBgFQgCgFABgHIAGg4IASABQAAAJAGADIAHADIALAAIBuABQAFAAADACQAEACABAEQABAEgBAHIgGA8IAMD3IgoAGgAhEBdIgqhjIgDgLIgBgHIACgIIAEgMIAFgPIAQgjIgNAAIgMAAQgGgBgDgDQgEgCgBgFQgCgEABgHIAGg6IASABQABAJAFADIAIADIALAAIBjAAIAMABIALADIAKAEIAIAGQAIAHAGAJIAFAJIAEAKIADAKIACALIABALIAAAMIAAAMIgBAMIgCANIgDANIgDANIgEAKIgFAMIgGALIgFAKIgHAJIgHAGIgHAFIgQAIIgSAGIhLATgAhEhWIgKAfIgCAJIAAAIIABAOIAFAPIATAnIAUgEIAzgPIANgFIAKgFIAIgGIAHgKIAGgLIADgLIABgLIAAgIIgCgHQgCgHgDgFQgDgFgFgEQgFgDgFgCIgMgDIgMgCIhPAAIgEAIgAE9BcIAFiiIgBgIQgBgGgEgEQgDgDgGgBIgPgCIhqAAIABC0IgoAGIAAAAIAPi6IgMgBQgGgBgDgCQgEgDgBgFQgBgFABgHIAGg4IASABQAAAJAGADIAHADIALAAICbABQAFAAAEACQADACABAEQABAEAAAHIgHA8IAKCkIgmAGg");
	this.shape_2.setTransform(1.5,151.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#076B94").s().p("ABtCGIAOiBIAXgJIAGACIgCCBIgoAIgAEVCFIAEiiIgBgIQgBgHgDgDQgEgDgGgCIgPgBIh0AAIgNgBQgFgBgEgDQgDgCgCgFQgBgFABgHIAGg5IASABQAAAJAGAEIAHADIALAAICEAAIAKABQAGAAADACQADACACAEQABAEgBAHIgHA8IALCkIgnAGgAAVCFIAFiMIAAgPIgBgLQgCgJgEgEQgFgFgGgBIgQgBIgPgBQgGgBgEgDQgEgCgCgFQgBgFABgHIAGg5IASABIABAIQACADACACIAGADIAGAAIABAAIANABIALADQAJADAGAHIAEAJIADALIACANIAAAPIAKC2IgoAGgAjvgDIgEAJIgCAJIgBAFIABAFIACAIIAGAOIALAXIgHA5Ig3ABIgEABIgEABIgCADIgRgDIAAAAIAKgwIACgIQACgDAEgBIAKgCIAYAAIgHgPIgDgLIgCgIIAAgFIABgFIADgKIAGgOIAJgSIgTgQIgMgKQgDgFgBgDQgCgDABgEIAJhLIATABIABAMQABAGAEAHQADAHAGAHIAHAIIAKAIIBOBDIAUgqIgLgBQgFgBgDgDQgDgCgBgEQgBgFAAgHIAGg6IASABQABAJAGAEIAHADIALAAIAuAAIABABIgJA9IgMABIgKACIgJAEIgHAFIgHAIIgHAKIgGANIgIAOIBGBCIgKBAIgNABg");
	this.shape_3.setTransform(1.4,100.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#076B94").s().p("AjBg1QgBgJgDgHQgDgGgGgEQgFgEgJgCIhMgKIgCAFIAAALQAAAFABADQABAEAEACQAEACAIACIAWADIABAAIgIA4IAAABIgegEIgLgCIgJgEQgIgDgEgGQgEgGAAgJIABgJIADgPIAEgSIAGgVIgKgDQgFgBgCgDQgDgCgBgFQgBgEABgGIAGg3IASABIACAIQABACACACIAHAEIANADIBbANQALACAHAIIAFAKIAEAMIACAPIABAPIAND9IgoAHgAg1BgIglhVIgFgOIgDgLIgBgIIACgIIAEgMIAFgPIAQgiIgNAAIgMgBQgGgBgDgCQgEgDgBgEQgBgFAAgHIAGg6IASABQABAJAFAEIAIACIALABIBjAAIAMABIALADIAKAEIAIAGQAIAGAGAJIAFAJIAEAKIADALIACAKIABAMIAAALIAAAMIgBAMIgCANIgDANIgDANIgEALIgFAMIgFALIgGAKIgHAIQgGAIgIAEIgQAHIgSAGIhLATgAg1hTIgKAeIgCAKIAAAHIABAOIAFAQIATAmIAUgDIAsgNIAHgDIANgFIAKgFIAIgGIAHgKIAGgKIADgMIABgLIAAgIIgCgHQgBgHgEgFQgDgFgFgDQgFgEgFgCIgMgDIgMgBIhPAAIgEAIgACPBbIAAAAIALgxIACgIQACgDADgCIALgBICAAAIAEgOIADgOIACgNIABgQIgBgNIgCgMIgEgLIgGgJQgEgEgFgDIgLgFQgHgDgIgBIgRgBIhAAAIgNgBQgGgBgDgDQgEgCgBgFQgCgFABgHIAGg5IASABQAAAJAGAEIAHACIALABIAzAAQAbAAARAJQARAJAJAQQAFAIADAJQAEAJACAKIACAUIABAXIAAARIgCARIgDANIgEAQIgEAQIgUA1IiJAAIgEABIgDABIgDACg");
	this.shape_4.setTransform(2.5,57.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#076B94").s().p("AleAFIAYgJIAGACIgCCBIgpAIgAhoCFIAkiYIABgNIgBgKQgBgEgDgDQgCgCgDgBIgIgBIgBAAIgNgBQgHAAgDgDQgFgDgBgFQgCgEABgIIAGg4IASAAIABABQAAAGACADQACAEAEABQAEABAHAAIAKABIAIACQAIADAEAFQAEAFACAHQACAIAAAJIgCAZIAigqIAGgLIAHgMIAyAAQAVABAOAKQANAKAHARIAHATIAEAUIACAWIAAAWIgKBsIgDAQIhxAAIgDABIgDABIgDADIgQgDIAAgBIALgwIACgIQACgDADgBIAJgCIBbAAIACgKIACgfIgBgQIgCgNIgEgNIgGgNQgHgLgNgGQgMgHgUAAIgRABIgOACIgLAEIgKAGIgJAHIgHAJIgFALIgFANIgMA0IgJBLIgoAGgAjECFIAEiZIAAgJIgBgIQgBgHgDgDQgDgDgGgBIgPgCIh1AAIgMgBQgGgBgEgCQgDgDgBgFQgCgFABgHIAGg4IASAAQAAAJAGAEIAHACIALABICPAAQAFABADACQAEACABAEQABAEgBAHIgGA8IAKCkIgnAGgACqCCIAAgBIALgxIADgIQABgDAEgBIAKgCICAAAIAFgNIADgPIABgPIABgQIgBgLIgCgMIgEgKIgGgJQgEgEgFgDIgLgGQgHgCgHgBIgSgCIhAAAIgNgBQgFgBgEgCQgEgDgBgFQgCgFABgHIAGg4IASAAQABAJAFAEIAIACIALABIAzAAQAaABARAIQARAJAKAQQAEAIAEAJQADAJACAKIADAVIAAAWIAAAPIgCARIgDAPIgDAQIgFAQIgUA1IiIAAIgFABIgDABIgDADg");
	this.shape_5.setTransform(2.9,6.5);

	this.addChild(this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-87.1,-196.7,173.7,404.8);


(lib.cf67yvuhp = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#FFFFFF","#E2E3E4"],[0.314,1],0,7.5,0,0,7.5,518).s().p("EhLxATiMAAAgnDMCXjAAAMAAAAnDg");
	this.shape.setTransform(485,125);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,970,250);


(lib.cf67uyp = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.cahracther2, null, new cjs.Matrix2D(1.43,0,0,1.43,-169.6,-127.9)).s().p("AldLDIAAkRQAHgVAQg6QAriaAYiBQAWiAAThPIAYhkQATgrAXgnQAZgrAjgkIAzgPIgUgvIAhgcIAGgUIAOgDIAIgZIgRgKIAAgKQAcgqAWgsIAeg6QAQgHAsgBQAsgBA2AIQAKANAFAPIABADIAnE8IgYAKQAJAQAIASQARAtALAvQAbB6AaB4IABAFIAAKkg");
	this.shape.setTransform(35.3,70.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0.2,0,70.2,141.5);


(lib.buiu = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#076B94").s().p("EgMfAu5MAAAhdxIY/AAMAAABdxgEgLSAtrIWkAAMAAAhbVI2kAAg");
	this.shape.setTransform(80.1,300.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,160.2,600.3);


(lib.vvvvvvvv = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// ball
	this.instance = new lib.Tween12("synched",0);
	this.instance.setTransform(334.4,-50.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({startPosition:0},9).to({startPosition:0},13).wait(1).to({y:-57.2},0).wait(1).to({y:-62.3},0).wait(1).to({y:-65.9},0).wait(1).to({y:-68},0).wait(1).to({y:-68.7},0).wait(1).to({y:-68.2},0).wait(1).to({y:-66.7},0).wait(1).to({y:-64.2},0).wait(1).to({y:-60.7},0).wait(1).to({y:-56.2},0).wait(1).to({y:-50.7},0).to({y:-55.2},2).to({y:-50.7},2).wait(43));

	// i
	this.instance_1 = new lib.Tween4("synched",0);
	this.instance_1.setTransform(335.5,6.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({startPosition:0},9).to({startPosition:0},10).wait(1).to({scaleY:1.05,y:4.6},0).wait(1).to({scaleY:1.09,y:3},0).wait(1).to({scaleY:1.12,y:1.8},0).wait(1).to({scaleY:1.14,y:1},0).wait(1).to({scaleY:1.15,y:0.8},0).wait(1).to({scaleY:1.14,y:1},0).wait(1).to({scaleY:1.13,y:1.5},0).wait(1).to({scaleY:1.11,y:2.3},0).wait(1).to({scaleY:1.08,y:3.5},0).wait(1).to({scaleY:1.04,y:5},0).wait(1).to({scaleY:1,y:6.8},0).to({startPosition:0},16).wait(34));

	// b
	this.instance_2 = new lib.Tween9("synched",0);
	this.instance_2.setTransform(283.8,-8.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({startPosition:0},9).to({startPosition:0},7).wait(1).to({scaleY:1.05,y:-11.6},0).wait(1).to({scaleY:1.09,y:-13.8},0).wait(1).to({scaleY:1.12,y:-15.5},0).wait(1).to({scaleY:1.14,y:-16.5},0).wait(1).to({scaleY:1.15,y:-16.8},0).wait(1).to({scaleY:1.14,y:-16.6},0).wait(1).to({scaleY:1.13,y:-15.9},0).wait(1).to({scaleY:1.11,y:-14.7},0).wait(1).to({scaleY:1.08,y:-13.2},0).wait(1).to({scaleY:1.04,y:-11.1},0).wait(1).to({scaleY:1,y:-8.6},0).to({startPosition:0},19).wait(34));

	// o
	this.instance_3 = new lib.Tween10("synched",0);
	this.instance_3.setTransform(210.7,7.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({startPosition:0},9).to({startPosition:0},4).wait(1).to({scaleY:1.05,y:5.4},0).wait(1).to({scaleY:1.09,y:3.8},0).wait(1).to({scaleY:1.12,y:2.6},0).wait(1).to({scaleY:1.14,y:1.9},0).wait(1).to({scaleY:1.15,y:1.7},0).wait(1).to({scaleY:1.14,y:1.8},0).wait(1).to({scaleY:1.13,y:2.3},0).wait(1).to({scaleY:1.11,y:3.1},0).wait(1).to({scaleY:1.08,y:4.3},0).wait(1).to({scaleY:1.04,y:5.7},0).wait(1).to({scaleY:1,y:7.6},0).to({startPosition:0},22).wait(34));

	// W
	this.instance_4 = new lib.Tween11("synched",0);
	this.instance_4.setTransform(119.6,-8);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({startPosition:0},9).to({scaleY:0.88,y:-1.3},3).wait(1).to({scaleY:1,y:-7.8},0).wait(1).to({scaleY:1.08,y:-12.5},0).wait(1).to({scaleY:1.13,y:-15.3},0).wait(1).to({scaleY:1.15,y:-16.2},0).wait(1).to({scaleY:1.14,y:-16},0).wait(1).to({scaleY:1.13,y:-15.3},0).wait(1).to({scaleY:1.11,y:-14.2},0).wait(1).to({scaleY:1.08,y:-12.6},0).wait(1).to({scaleY:1.04,y:-10.5},0).wait(1).to({scaleY:1,y:-8},0).to({startPosition:0},24).wait(34));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(62.4,-64.4,286.3,156.1);


(lib.Tween2 = function() {
	this.initialize();

	// Layer 2
	this.instance = new lib.vvvvvvvv();
	this.instance.setTransform(0.1,-24.1,1.153,1.153,0,0,0,205.5,-8.1);

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#403F3F").s().p("AnYB0IgPgBIgPgDIgNgGIgNgIIgLgKIgJgMIgIgPIgFgSIgEgVIgBgWQAAgfAIgXQAHgWAMgMIgXACIgBgBIAAgYIArgDIAwgBQArAAAaAdQAZAdAAA5IgBAWIgEAVIgFASQgEAIgEAHIgJAMIgMAKIgMAIIgNAGIgPADIgPABIAAAAgAnYhZIghAAQgOAPgHAZQgEANgCAMQgBAMAAAKIAAASIACASIAEAPIAGANQAHAOAMAHQAMAIASAAQARAAANgIQAMgHAHgOQAMgZAAglQAAgwgRgXIgIgHIgKgGIgMgEIgOgBIAAAAgAqwB0IgQgBIgOgBIgLgBIgHgCIgFgCIgBgaIABAAQAYAHAdAAIALgBIAKgCQAJgDAGgFQAGgFAFgGQAEgHADgHIAEgNIABgLIABgMIAAggIgBgVQgCgJgCgHQgCgHgFgHQgEgHgHgFQgGgFgJgDIgLgDIgNgBIgNABIgOACIgLACIgIACIgFACIgBAAIAAgaIAHgCIAGgCIALgCIAOgCIAQgBIAPABIAOADIAMAEIAKAFIAJAHIAIAHIAGAIIAFAJIAEAJIAEAJIADARIACASIAAAkIgBALIgBAMIgDALIgDAKIgEAJIgGAKIgIAJIgIAIIgLAHIgOAGIgQAEIgRABgAOnBwIAAAAIAAgXIAAAAIAzAAIAAh/QAAgagMgNQgNgNgZAAIgJABIgIACQgJADgFAEIgLAIIgHAHIgCADIgRCuIggAAIAAAAIARirIAAgEIAAgFIgCgLIgDgLIgEgKIgFgLIABAAIAfAAIAFAKIAEANIAAAAIALgKIANgHIAIgEIALgDIALgCIANgBQAjAAASAUQASAUAAAjIAACYIAAAAgAJJBwIgUjfIAAAAIAgAAIALB7IAZgHQAcgHAEgnIAIhGIAfAAIAAAAIgGA7IgBAMIgCAKIgDAJIgEALIgFAJIgGAHIgIAHIgKAHIgLAFIgOAFIgYAFIAFA2IA3AAQAmAAAZgaQAagZAFgzIAJhiIAgAAIAAAAIgJBiIgDAUIgFASIgGARIgGAMIgHALIgJALIgLALIgMAIIgOAHIgRAFIgUAEIgVABgAH3BwIAAAAIAAjfIAfAAIAADfIAAAAgAGtBwIAAAAIAAjfIAAAAIAfAAIAAAAIAADfIAAAAgACBBwIgBAAIAAjeQARgCAVgBIAtgCQAvAAAYAQQAXAPAAAfIAAClIAAAAgAC6hZIgTABIgHAAIAACxIBxAAIAAiKIgBgKIgDgIQgDgIgGgEIgHgEIgJgDIgJgCIgIgBIgJAAIgKgBgAgfBwIAAAAIAAjfIAAAAIAfAAIAAAAIAADfIAAAAgAhwBwIAAAAIAAibQAAgXgRgMQgQgMgiAAIguACIAADIIgBAAIgfAAIAAAAIAAjgIArgCIAogBQAhAAAXAKQAYALAJAXIAEANIABAPIAACbIgBAAgAlSBwIgBAAIAAjfIABAAIAfAAIAAAAIAADfIAAAAgAv4BwIgBAAIAAjeQARgCAVgBIAtgCQAvAAAXAQQAYAPAAAfIAAClIAAAAgAu/hZIgTABIgHAAIAACxIBxAAIAAiKIgBgKIgDgIQgDgIgGgEQgGgFgKgCIgJgCIgIgBIgJAAIgKgBgAFaAkIgBAAIAAiTIAgAAIAAAAIAAB1IgZAegAsjAkIAAAAIAAiTIAfAAIAAB1IgYAeg");
	this.shape.setTransform(1.5,70.7,1.577,1.577);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-164.9,-89,330,178.1);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.instance = new lib.dct7vyp();
	this.instance.setTransform(-105,-0.7,1,1,0,0,0,21.3,9.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-121.5},4).to({x:-105},5).wait(1));

	// Layer 5
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEjC2IgBgCIAAj7IABgCIA5AAIACACIAAD7IgCACgAjZBeIAAgwIBBgLIg4jTIABgBIA+AAIAvDEQAOgKAIgPQAJgTAEgdIAKh6IA9AAIgIByQgCARgEAPIgGAbQgfBFhcAQIhRAMgAmLBWQgTgBgPgEIAAgyIBEAEQAhAAAJgZQAIgNgBgWIAAgrQgBgtgZgNQgKgFgNAAIhEAFIAAgyQASgDATAAIAmgBQAYgBASAHQAUAHAMAMQAJAKAJARQAHAOAEARQADASAAASIAAAdQAAATgCAPQgDAPgHASQgHAOgMANQgMAKgTAHQgTAHgZAAIgpAAgAMBBSIgCgBIAAguIACgCIByAAIAAh4QAAgsgxAAIhBAFIgCgCIAAgwQAQgDASAAIAqgBQBAAAAWAZQALAOAEARQACARAAAWIAAB2IAdAAIADACIAAAuIgDABgAKABSIgBgBIAAifQAAgLADgJQAEgLAFgFQAGgJAIgDIiHgCIAAgxIDOAAIACABIAAAtQgKADgIAHQgKAHgDAKQgFALAAAPIAACggAGABSIgCgBIAAgIQABgPAEgdQAFgdAKgSIAnhuIiWAAIgBgCIAAguIDbgBIACABIAAAmIgtB2QgKAZgFAaQgGAXAAATIAAAJgAClBSIAAkDIA9AAIADABIAAEBIgDABgArRBSIgXkCIAAgBIA8AAIAMCBIAFAAQANABAJgHQAHgJABgSIAIhfIA7gBIACABIgGBdQgIBQhMAAIgLAAIAEAkIA/AAQAhAAATgZQAHgMAGgSQAFgRACgWIAKhzIA8gBIACABIgKByQgEAjgHAWQgcBYhhgBgAvPBSIgCgBIAAkBIACgBIA8AAIACABIAAEBIgCABgAtVgDIAAiuIA9AAIACABIAAB4IgqA1g");
	this.shape.setTransform(33.7,2.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(10));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F39122").s().p("AvtE2IAAprIAAAAIfaAAIABAAIAAJrIgBAAg");
	this.shape_1.setTransform(0,-0.1,1.577,1.577);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(10));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-158.7,-49,317.4,98);


(lib.cv657yp = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Bitmap1, null, new cjs.Matrix2D(-0.442,-0.897,0.897,-0.442,-36.6,296.2)).s().p("AgzZxQgzgHgrgcQgbgSgKgdQgFgQgBgQQgDg0AAgzQABg5AFg5IAEguQACg+AEg+IAJh1IAKh2QADggAAggQABg1ACg1QADg5AFg6QAFg6ACg5IABg1QAAgXghgZQghgZAAghQAAgiA+g+QBAg/ADgpIAAjNIANhzQAAgKgHgIIAAgTQAChSAEgnIAAgoQADgLAAgfIAAgEIACgQIAAgvIABgBIAAhLQAFhHAAglIAAgfIAAgEIAAgDIgBgBQgBgKgGAEIgRgHIgMgGIgCgEIgFgMQAMg1ADgTQACgOACgbQACgdACgMIAAgkIAAgFIABgFIgBgEQABgxAIhCQAFgmACgbQABgPAFgaIAEgRIAHgIQAQgQAAgFQAAgEgDgFQgDgFAAgDQAAgCAHgPQAGgQAAgNQAAgTgHgQQgGgQgRgWQgGgIgLgjIgCgFIgFgUQgGgaAAgPIABgNIgCgNQAAgFADgGQADgGABgHIABgZIAAgoQABgMAIgoIAHgiIADgEIAKAAQAUARAAAaIABArQADAOALAeQACAHANADQANADADAFQABAKABAEQACAFAZABQABABAFAKQAEAHAZAAQAFAAAJALIAIAHIgDAKIgEAdIgHAaQgEAPgGALQgGAPgbAqQgMATAAAcQAAAMAGAJQAHAJAAAFQAAAFgGAFQgGAEAAAHQAAAIAMAKQAOAMAEANIAHAZIACAFIAEANIAGAXQADAhADASQADAQAEAiIAGA0QAEAVAHBQQADATAJAgQAEANAHAOIACADIgCAEQgDAJgFAEQgMALggAFQgPACgCAEQgBABAAAEIgCAGIAAAMQAAASADALQACALAAAPIABAsQAAAPADAnIAGBiIAAAzQABACAAAHIAAAAQAAAFgDADQgDADAAADIABAIIAAAqIABACIAAA2QgCAgABAtIAEBNIAAAmQAAADADACQgDA+AAArIAABNQABArAJAeQACAJAyBCQAvBAAAAOQAAAagaAnIgSAbQgPALgEAMQgCATAAAiQgCAcACAcIABAYQABCQAFCQIABAZIADBQQABA0AEA2IAHBtIAGBmIAEBeIABBjQABA7gjAwQgFAIgIAEQgmAWgpAKQgbAGgZAAQgVAAgWgEg");
	this.shape.setTransform(-1.8,119.5);

	// Layer 2
	this.instance = new lib.g67y9p();
	this.instance.setTransform(2.9,-36.1,1,1,-4.5,0,0,23.4,12.4);
	this.instance.alpha = 0.27;

	this.addChild(this.instance,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-22,-50.5,77.1,342.9);


(lib.credit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_49 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(49).call(this.frame_49).wait(1));

	// Layer 1
	this.instance = new lib.f67y9p();
	this.instance.setTransform(1.9,21.6,1,1,0,0,0,1.9,21.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(39).to({alpha:0},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,3.7,43.3);


(lib._67yp = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.buiu();
	this.instance.setTransform(485,125,1,1,0,0,0,485,125);

	this.instance_1 = new lib.cf67yvuhp();
	this.instance_1.setTransform(80,300,0.619,0.64,90,0,0,485,125);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,160.2,600.3);


// stage content:



(lib._160x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		document.body.style.margin = 0;
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(276));

	// credit
	this.instance = new lib.credit();
	this.instance.setTransform(13,33.8,1.166,1.166);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(276));

	// Layer 4
	this.instance_1 = new lib.cv657yp();
	this.instance_1.setTransform(73.4,678.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({regX:16.5,regY:120.9,rotation:0.1,x:90.4,y:794},0).wait(1).to({rotation:0.5,x:91.8,y:776.2},0).wait(1).to({rotation:1.2,x:94.4,y:744.7},0).wait(1).to({rotation:2.2,x:98.1,y:699.2},0).wait(1).to({rotation:3.5,x:102.8,y:641.9},0).wait(1).to({rotation:4.9,x:107.8,y:579.9},0).wait(1).to({rotation:6.1,x:112.3,y:524.9},0).wait(1).to({rotation:6.9,x:115.3,y:488.4},0).wait(1).to({regX:0,regY:0,rotation:7.2,x:115.1,y:354.1},0).wait(1).to({regX:16.5,regY:120.9,rotation:7,x:115.5,y:476},0).wait(1).to({rotation:6.3,x:112.7,y:475.7},0).wait(1).to({rotation:5,x:107.3,y:475.3},0).wait(1).to({rotation:2.9,x:98.7,y:474.3},0).wait(1).to({rotation:0.4,x:88.7,y:473},0).wait(1).to({rotation:-1.6,x:80.5,y:471.8},0).wait(1).to({rotation:-2.9,x:75.2,y:470.9},0).wait(1).to({rotation:-3.6,x:72.5,y:470.4},0).wait(1).to({regX:0,regY:0,rotation:-3.8,x:47.4,y:350.7},0).wait(1).to({regX:16.5,regY:120.9,rotation:-2.4,x:77.7,y:476.3},0).wait(1).to({rotation:3.5,x:102.8,y:501.2},0).wait(1).to({rotation:8,x:122.2,y:519.4},0).wait(1).to({regX:0,regY:0,rotation:9,x:128.9,y:401.3},0).wait(1).to({regX:16.5,regY:120.9,rotation:8.6,x:124.6,y:523.1},0).wait(1).to({rotation:7,x:118.1,y:522.4},0).wait(1).to({rotation:3.5,x:104,y:520.5},0).wait(1).to({rotation:-1.1,x:85.3,y:517.4},0).wait(1).to({rotation:-4.2,x:72.6,y:514.7},0).wait(1).to({rotation:-5.6,x:66.8,y:513.4},0).wait(1).to({regX:0,regY:0,rotation:-6,x:36.2,y:394.6},0).to({rotation:10.4,x:120.4,y:446.5},5).wait(1).to({regX:16.5,regY:120.9,rotation:10.2,x:113.8,y:568.3},0).wait(1).to({rotation:9.3,x:110.4},0).wait(1).to({rotation:7.4,x:103.5},0).wait(1).to({rotation:4.6,x:92.9,y:567.9},0).wait(1).to({rotation:1.5,x:81.4,y:567.2},0).wait(1).to({rotation:-0.8,x:72.9,y:566.5},0).wait(1).to({rotation:-2.2,x:67.9,y:565.9},0).wait(1).to({rotation:-2.8,x:65.4,y:565.7},0).wait(1).to({regX:0,regY:0,rotation:-3,x:41.9,y:445.7},0).wait(1).to({regX:16.5,regY:120.9,rotation:-2.8,x:65.7,y:574},0).wait(1).to({rotation:-1.8,x:70.3,y:612.7},0).wait(1).to({rotation:0.6,x:80.8,y:701.8},0).wait(1).to({rotation:2.2,x:87.9,y:762.6},0).wait(1).to({rotation:2.8,x:90.6,y:785.4},0).wait(1).to({regX:0,regY:0,rotation:2.9,x:81,y:669.4},0).to({_off:true},1).wait(21).to({_off:false,rotation:0,x:65.9,y:659.1},0).wait(1).to({regX:16.5,regY:120.9,rotation:0.2,x:83.1,y:770.6},0).wait(1).to({rotation:0.9,x:85.6,y:738.9},0).wait(1).to({rotation:2.2,x:89.9,y:682.2},0).wait(1).to({rotation:3.8,x:95.5,y:609.3},0).wait(1).to({rotation:5.3,x:100.8,y:541.2},0).wait(1).to({rotation:6.3,x:104.5,y:493.3},0).wait(1).to({rotation:6.9,x:106.5,y:467.6},0).wait(1).to({regX:0,regY:0,rotation:7,x:105.5,y:337.9},0).wait(1).to({regX:16.5,regY:120.9,rotation:6.7,x:106.1,y:460},0).wait(1).to({rotation:5.6,x:102.7,y:460.3},0).wait(1).to({rotation:3.5,x:96.4,y:460.6},0).wait(1).to({rotation:0.8,x:88.6,y:460.7},0).wait(1).to({rotation:-1.2,x:82.5},0).wait(1).to({rotation:-2.3,x:79.2,y:460.6},0).wait(1).to({regX:0,regY:0,rotation:-2.7,x:56.2,y:340.6},0).wait(1).to({regX:16.5,regY:120.9,rotation:-2,x:80.9,y:463.8},0).wait(1).to({rotation:0.4,x:90.5,y:475.6},0).wait(1).to({rotation:3.9,x:104.7,y:492.7},0).wait(1).to({rotation:6.1,x:114,y:503.6},0).wait(1).to({regX:0,regY:0,rotation:6.8,x:114.4,y:384.6},0).wait(1).to({regX:16.5,regY:120.9,rotation:6.5,x:115.8,y:506.4},0).wait(1).to({rotation:5.7,x:113.3,y:506},0).wait(1).to({rotation:4.2,x:108.8,y:505.1},0).wait(1).to({rotation:2.1,x:102.5,y:503.7},0).wait(1).to({rotation:0,x:96.2,y:502.2},0).wait(1).to({rotation:-1.4,x:91.8,y:501},0).wait(1).to({rotation:-2.2,x:89.4,y:500.3},0).wait(1).to({regX:0,regY:0,rotation:-2.5,x:67.1,y:380.1},0).wait(1).to({regX:16.5,regY:120.9,rotation:-1.9,x:90,y:502.9},0).wait(1).to({rotation:-0.1,x:94.4,y:512.6},0).wait(1).to({rotation:3.2,x:102.1,y:529.2},0).wait(1).to({rotation:6.4,x:109.7,y:545.2},0).wait(1).to({rotation:8.2,x:113.9,y:554},0).wait(1).to({regX:0,regY:0,rotation:8.8,x:117.2,y:434.5},0).wait(1).to({regX:16.5,regY:120.9,rotation:8.5,x:114.3,y:556.3},0).wait(1).to({rotation:7.8,x:111.5,y:555.9},0).wait(1).to({rotation:6.5,x:106.3,y:555.1},0).wait(1).to({rotation:4.5,x:98.6,y:553.8},0).wait(1).to({rotation:2.2,x:89.8,y:552.1},0).wait(1).to({rotation:0.3,x:82.3,y:550.5},0).wait(1).to({rotation:-1,x:77.1,y:549.3},0).wait(1).to({rotation:-1.7,x:74.4,y:548.7},0).wait(1).to({regX:0,regY:0,rotation:-1.9,x:53.1,y:428.2},0).wait(1).to({regX:16.5,regY:120.9,rotation:-1.4,x:77.1,y:552},0).wait(1).to({rotation:0.7,x:89.5,y:564.9},0).wait(1).to({rotation:3.7,x:107.9,y:583.6},0).wait(1).to({rotation:5.7,x:119.9,y:595.7},0).wait(1).to({regX:0,regY:0,rotation:6.3,x:120,y:477},0).wait(1).to({regX:16.5,regY:120.9,rotation:6,x:121.7,y:598.9},0).wait(1).to({rotation:5,x:116.6,y:598.6},0).wait(1).to({rotation:3.2,x:107.1,y:597.8},0).wait(1).to({rotation:1,x:95.4,y:596.8},0).wait(1).to({rotation:-0.8,x:86.1,y:595.8},0).wait(1).to({rotation:-1.7,x:81.1,y:595.2},0).wait(1).to({regX:0,regY:0,rotation:-2,x:59,y:474.8},0).wait(1).to({regX:16.5,regY:120.9,rotation:-1.1,x:86.5,y:601},0).wait(1).to({rotation:2.2,x:110.4,y:621.5},0).wait(1).to({rotation:5.4,x:133.8,y:641.1},0).wait(1).to({regX:0,regY:0,rotation:6.3,x:137.2,y:524.7},0).wait(1).to({regX:16.5,regY:120.9,rotation:5.9,x:138.6,y:646.4},0).wait(1).to({rotation:4.8,x:132.3,y:645.8},0).wait(1).to({rotation:2.6,x:120.6,y:644.5},0).wait(1).to({rotation:-0.5,x:104.2,y:642.4},0).wait(1).to({rotation:-3.4,x:88,y:640},0).wait(1).to({rotation:-5.6,x:76.5,y:638.1},0).wait(1).to({rotation:-6.7,x:70.4,y:637},0).wait(1).to({regX:0,regY:0,rotation:-7,x:37.6,y:518.7},0).wait(1).to({regX:16.5,regY:120.9,x:73.5,y:652.1},0).wait(1).to({x:90.2,y:705.5},0).wait(1).to({x:106.5,y:757.9},0).wait(1).to({regX:0,regY:0,x:80.1,y:654.7},0).to({_off:true},1).wait(133));

	// fold
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FCF7EE","#D9D2C9","#FFF5E9"],[0.161,0.514,0.851],3.7,-10.6,-3.9,-5.2).s().p("AhQhQIChAHQgHBuAHAsg");
	this.shape.setTransform(7.7,579.2,1,2.385);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FCF7EE","#DBD4CB","#FFF5E9"],[0.161,0.514,0.851],4.3,-25.3,-5.9,-11).s().p("Ah4n3IDxJQQgrDsAMCzg");
	this.shape_1.setTransform(11.8,548.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#FCF7EE","#DED6CD","#FFF5E9"],[0.161,0.514,0.851],5,-25.3,-7.9,-9.7).s().p("AihstIFDSRQhPDMARD+g");
	this.shape_2.setTransform(15.9,517.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#FCF7EE","#E0D9D0","#FFF5E9"],[0.161,0.514,0.851],5.7,-25.3,-9.9,-8.3).s().p("AjJxjIGUbSQhzCsAWFJg");
	this.shape_3.setTransform(20,486.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#FCF7EE","#E2DBD2","#FFF5E9"],[0.161,0.514,0.851],6.4,-25.4,-11.8,-7).s().p("Ajy2ZMAHlAkTQiWCNAaGTg");
	this.shape_4.setTransform(24.1,455.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#FCF7EE","#E5DDD4","#FFF5E9"],[0.161,0.514,0.851],7.2,-25.4,-13.7,-5.7).s().p("Aka7OMAI1AtTQi5BuAfHcg");
	this.shape_5.setTransform(28.2,424.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#FCF7EE","#E7DFD6","#FFF5E9"],[0.161,0.514,0.851],7.9,-25.4,-15.7,-4.3).s().p("EgFDggFMAKHA2VQjdBOAkIog");
	this.shape_6.setTransform(32.3,393.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#FCF7EE","#E9E2D9","#FFF5E9"],[0.161,0.514,0.851],8.5,-25.5,-17.7,-3).s().p("EgFsgk7MALYA/WQkBAuAqJyg");
	this.shape_7.setTransform(36.4,362.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["#FCF7EE","#ECE4DB","#FFF5E9"],[0.161,0.514,0.851],9.2,-25.5,-19.6,-1.7).s().p("EgGUgpwMAMpBIWQklAOAuK+g");
	this.shape_8.setTransform(40.5,331.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["#FCF7EE","#EEE6DD","#FFF5E9"],[0.161,0.514,0.851],9.9,-10.7,-21.6,-0.1).s().p("Am9ziMAN7AiHQlJgHAzFFg");
	this.shape_9.setTransform(44.6,300.6,1,2.385);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["#FCF7EE","#EDE6DD","#FFF5E9"],[0.161,0.514,0.851],11.1,-28.7,-28.3,8.1).s().p("EgIOgvCMAQdBPSQnFg+AYPxg");
	this.shape_10.setTransform(62.7,297.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#FCF7EE","#EDE6DD","#FFF5E9"],[0.161,0.514,0.851],12.3,-31.9,-35,16.5).s().p("EgJggveMATABNNQpAhsgFTcg");
	this.shape_11.setTransform(80.8,295);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["#FCF7EE","#ECE5DD","#FFF5E9"],[0.161,0.514,0.851],13.5,-35.1,-41.7,24.9).s().p("EgKxgv6MAVjBLIQq7iZggXGg");
	this.shape_12.setTransform(99,292.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["#FCF7EE","#ECE5DD","#FFF5E9"],[0.161,0.514,0.851],14.8,-38.3,-48.3,33.4).s().p("EgMDgwWMAYHBJDQs4jHg8axg");
	this.shape_13.setTransform(117.1,289.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["#FCF7EE","#EBE5DD","#FFF5E9"],[0.161,0.514,0.851],16.1,-41.5,-55,41.7).s().p("EgNUgwyMAapBG9Qu0jzhXebg");
	this.shape_14.setTransform(135.2,286.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["#FCF7EE","#EAE5DD","#FFF5E9"],[0.161,0.514,0.851],17.3,-44.7,-61.6,50.1).s().p("EgOmgxOMAdNBE4UgQwgEggB0AiFg");
	this.shape_15.setTransform(153.3,283.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["#FCF7EE","#EAE4DD","#FFF5E9"],[0.161,0.514,0.851],18.5,-47.9,-68.3,58.5).s().p("EgP3gxqMAfvBCzUgSsgFNgCPAlvg");
	this.shape_16.setTransform(171.5,281.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["#FCF7EE","#E9E4DD","#FFF5E9"],[0.161,0.514,0.851],19.7,-51.1,-75,66.9).s().p("EgRJgyFMAiTBAtUgUpgF7gCrApag");
	this.shape_17.setTransform(189.6,278.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["#FCF7EE","#EAE5DE","#FFF5E9"],[0.161,0.514,0.851],19.4,-65.1,-89,69.9).s().p("EgSvg0KMAlfBE9UgX1gHvgCrArHg");
	this.shape_18.setTransform(207.7,265.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.lf(["#FCF7EE","#EBE6DE","#FFF5E9"],[0.161,0.514,0.851],19,-79.1,-103.1,72.9).s().p("EgUVg2OMAorBJLUgbBgJigCrAs0g");
	this.shape_19.setTransform(225.8,251.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.lf(["#FCF7EE","#EBE6DF","#FFF5E9"],[0.161,0.514,0.851],18.7,-93.2,-117,75.8).s().p("EgV7g4SMAr3BNaUgeNgLWgCsAuhg");
	this.shape_20.setTransform(243.9,238.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.lf(["#FCF7EE","#ECE7E0","#FFF5E9"],[0.161,0.514,0.851],18.4,-107.2,-131,78.8).s().p("EgXhg6WMAvEBRpUghbgNKgCqAwOg");
	this.shape_21.setTransform(262,225.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.lf(["#FCF7EE","#EDE8E0","#FFF5E9"],[0.161,0.514,0.851],18,-121.2,-145.1,81.9).s().p("EgZIg8aMAyRBV4UgkngO+gCrAx7g");
	this.shape_22.setTransform(280.1,212.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.lf(["#FCF7EE","#EEE9E1","#FFF5E9"],[0.161,0.514,0.851],17.7,-135.2,-159.1,84.8).s().p("Egaug+eMA1dBaGUgnzgQxgCrAzog");
	this.shape_23.setTransform(298.2,199);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.lf(["#FCF7EE","#EEE9E2","#FFF5E9"],[0.161,0.514,0.851],17.4,-149.3,-173,87.8).s().p("EgcUhAjMA4pBeWUgq/gSlgCrA1Wg");
	this.shape_24.setTransform(316.3,185.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.lf(["#FCF7EE","#EFEAE2","#FFF5E9"],[0.161,0.514,0.851],17,-163.3,-187.1,90.7).s().p("Egd6hCnMA71BilUguLgUZgCrA3Dg");
	this.shape_25.setTransform(334.4,172.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.lf(["#FCF7EE","#F0EBE3","#FFF5E9"],[0.161,0.514,0.851],16.7,-177.4,-201.1,93.7).s().p("EgfhhErMA/CBm0UgxYgWNgCrA4wg");
	this.shape_26.setTransform(352.6,159.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.lf(["#FCF7EE","#F0EBE3","#FFF5E9"],[0.161,0.514,0.851],16.7,-177.4,-201.1,93.7).s().p("EgfhhErMA/CBm0UgxXgWNgCsA4wg");
	this.shape_27.setTransform(352.6,159.4);
	this.shape_27._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},50).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_27}]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.shape_27).wait(77).to({_off:false},0).wait(199));

	// fold
	this.instance_2 = new lib.vy78by();
	this.instance_2.setTransform(12.9,571.1,0.372,0.388,0,-2.1,-77.8,128.4,153);
	this.instance_2.alpha = 0.34;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(50).to({_off:false},0).to({regX:128.6,regY:153.1,scaleX:0.38,scaleY:3.03,skewX:-4,skewY:-2.4,x:66.3,y:403.9},9).to({regX:128.5,regY:153,scaleX:1.03,scaleY:2.37,skewX:2.9,skewY:16.3,x:207,y:309.6,alpha:0.422},8).to({scaleX:2.93,scaleY:2.31,skewX:16.8,x:431.9,y:353.4},9).wait(200));

	// mask page 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_50 = new cjs.Graphics().p("Eg8tBU2MhH6iprMDBVAAAMBH6Cprg");
	var mask_graphics_51 = new cjs.Graphics().p("EhF1BVCMgfdiqDMCrIAAAMAfdCqDg");
	var mask_graphics_52 = new cjs.Graphics().p("EhGLBVAMgcOip/MColAAAMAcOCp/g");
	var mask_graphics_53 = new cjs.Graphics().p("EhGhBU8MgY/ip3MCmCAAAMAY/Cp3g");
	var mask_graphics_54 = new cjs.Graphics().p("EhG2BU2MgVyiprMCjfAAAMAVyCprg");
	var mask_graphics_55 = new cjs.Graphics().p("EhGiBT2MgUyinrMCh3AAAMAUyCnrg");
	var mask_graphics_56 = new cjs.Graphics().p("EhGOBS0MgTzilnMCgQAAAMATzClng");
	var mask_graphics_57 = new cjs.Graphics().p("EhF5BRzMgS2ijlMCepAAAMAS2Cjlg");
	var mask_graphics_58 = new cjs.Graphics().p("EhFjBQyMgR6ihjMCdBAAAMAR6Chjg");
	var mask_graphics_59 = new cjs.Graphics().p("EhFNBPwMgQ/iffMCbaAAAMAQ/Cffg");
	var mask_graphics_60 = new cjs.Graphics().p("EhCzBPwMgQ/iffMCWmAAAMAQ/Cffg");
	var mask_graphics_61 = new cjs.Graphics().p("EhASBPwMgQ/iffMCRzAAAMAQ/Cffg");
	var mask_graphics_62 = new cjs.Graphics().p("Eg9CBPwMgQ/iffMCM/AAAMAQ/Cffg");
	var mask_graphics_63 = new cjs.Graphics().p("Eg5yBPwMgQ/iffMCILAAAMAQ/Cffg");
	var mask_graphics_64 = new cjs.Graphics().p("Eg2iBPwMgQ/iffMCDXAAAMAQ/Cffg");
	var mask_graphics_65 = new cjs.Graphics().p("EgzSBPwMgRAiffMB+kAAAMAQ/Cffg");
	var mask_graphics_66 = new cjs.Graphics().p("EgwDBPwMgQ/iffMB5wAAAMAQ/Cffg");
	var mask_graphics_67 = new cjs.Graphics().p("EgszBPwMgQ/iffMB08AAAMAQ/Cffg");
	var mask_graphics_68 = new cjs.Graphics().p("EgsNBPwMgQjiffMB08AAAMAQjCffg");
	var mask_graphics_69 = new cjs.Graphics().p("EgroBPwMgQGiffMB09AAAMAQFCffg");
	var mask_graphics_70 = new cjs.Graphics().p("EgrCBPwMgPpiffMB08AAAMAPpCffg");
	var mask_graphics_71 = new cjs.Graphics().p("EgqdBPwMgPMiffMB08AAAMAPMCffg");
	var mask_graphics_72 = new cjs.Graphics().p("Egp3BPwMgOwiffMB08AAAMAOwCffg");
	var mask_graphics_73 = new cjs.Graphics().p("EgpRBPwMgOTiffMB08AAAMAOTCffg");
	var mask_graphics_74 = new cjs.Graphics().p("EgosBPwMgN2iffMB08AAAMAN2Cffg");
	var mask_graphics_75 = new cjs.Graphics().p("EgoGBPwMgNaiffMB08AAAMANaCffg");
	var mask_graphics_76 = new cjs.Graphics().p("EgnhBPwMgM9iffMB08AAAMAM9Cffg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(50).to({graphics:mask_graphics_50,x:522.4,y:328.7}).wait(1).to({graphics:mask_graphics_51,x:518.6,y:328.8}).wait(1).to({graphics:mask_graphics_52,x:520.9,y:328.7}).wait(1).to({graphics:mask_graphics_53,x:523.2,y:328.7}).wait(1).to({graphics:mask_graphics_54,x:525.6,y:328.7}).wait(1).to({graphics:mask_graphics_55,x:526.8,y:328.7}).wait(1).to({graphics:mask_graphics_56,x:528,y:328.6}).wait(1).to({graphics:mask_graphics_57,x:529.2,y:328.5}).wait(1).to({graphics:mask_graphics_58,x:530.4,y:328.5}).wait(1).to({graphics:mask_graphics_59,x:531.7,y:328.7}).wait(1).to({graphics:mask_graphics_60,x:527.1,y:328.7}).wait(1).to({graphics:mask_graphics_61,x:521.8,y:328.7}).wait(1).to({graphics:mask_graphics_62,x:511.8,y:328.7}).wait(1).to({graphics:mask_graphics_63,x:501.8,y:328.7}).wait(1).to({graphics:mask_graphics_64,x:491.8,y:328.7}).wait(1).to({graphics:mask_graphics_65,x:481.8,y:328.7}).wait(1).to({graphics:mask_graphics_66,x:471.8,y:328.7}).wait(1).to({graphics:mask_graphics_67,x:461.8,y:328.7}).wait(1).to({graphics:mask_graphics_68,x:465.5,y:328.7}).wait(1).to({graphics:mask_graphics_69,x:469.3,y:328.7}).wait(1).to({graphics:mask_graphics_70,x:473,y:328.7}).wait(1).to({graphics:mask_graphics_71,x:476.8,y:328.7}).wait(1).to({graphics:mask_graphics_72,x:480.6,y:328.7}).wait(1).to({graphics:mask_graphics_73,x:484.3,y:328.7}).wait(1).to({graphics:mask_graphics_74,x:488.1,y:328.7}).wait(1).to({graphics:mask_graphics_75,x:491.8,y:328.7}).wait(1).to({graphics:mask_graphics_76,x:495.6,y:328.7}).wait(200));

	// page1
	this.instance_3 = new lib.fvyuibgyiuyo();
	this.instance_3.setTransform(80.1,337.1);

	this.instance_4 = new lib.cf67uyp();
	this.instance_4.setTransform(81.1,165.6,0.652,0.652,0,0,0,36.3,96.6);

	this.instance_5 = new lib.gbuiuhiop();
	this.instance_5.setTransform(83.9,146.7,0.652,0.652,0,0,0,176.3,125.4);

	this.instance_6 = new lib.bg();
	this.instance_6.setTransform(0,600,0.619,0.64,-90);

	this.instance_3.mask = this.instance_4.mask = this.instance_5.mask = this.instance_6.mask = mask;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3}]}).wait(276));

	// but
	this.instance_7 = new lib.Tween1("synched",0);
	this.instance_7.setTransform(233.9,473.7,0.388,0.388);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(228).to({_off:false},0).to({x:77.9},10,cjs.Ease.get(1)).wait(38));

	// logo
	this.instance_8 = new lib.Tween2("synched",0);
	this.instance_8.setTransform(-76.3,544.7,0.389,0.389);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(228).to({_off:false},0).to({x:77.7},10,cjs.Ease.get(1)).wait(38));

	// text3
	this.instance_9 = new lib.ftyugyuop();
	this.instance_9.setTransform(79.1,761);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(151).to({_off:false},0).to({y:282.5},13,cjs.Ease.get(1)).wait(64).to({y:239.6},5).wait(43));

	// text2
	this.instance_10 = new lib.dc7yvt9p();
	this.instance_10.setTransform(81.5,265.2);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(50).to({_off:false},0).wait(98).to({y:-229.8},13).wait(115));

	// frame
	this.instance_11 = new lib._67yp();
	this.instance_11.setTransform(485,125,1,1,0,0,0,485,125);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(148).to({_off:false},0).to({alpha:1},13).wait(115));

	// page 2
	this.instance_12 = new lib.bg();
	this.instance_12.setTransform(0,600,0.619,0.64,-90);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(50).to({_off:false},0).wait(226));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(80,300,160,971);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;